name: Golang Meetup Map
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  
permissions:
 contents: write
jobs:
  test-and-validate: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
      - run: go test ./...
      - run: echo "✅ Tests Passed Successfully "
  archive-meetups-create-pr:
    needs: test-and-validate
    if: github.ref == 'refs/heads/main'
    concurrency: ci-${{ github.ref }} 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
      - run: go run ./cmd/archive/main.go -root ${{github.workspace}}    
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
